### ISSUE TITLE
Buggy flattener!

### ISSUE THREAD

**Issue by alecjacobson** [psarahdactyl/wysiwyc#2]
Oh no! This time it finished but the output looks weird.

Here's the input:
[art.svg.zip](https://github.com/psarahdactyl/wysiwyc/files/2413025/art.svg.zip)

![image](https://user-images.githubusercontent.com/2241689/45981343-a7b6db80-c022-11e8-8c01-992393216359.png)

But this is the output :-(

![image](https://user-images.githubusercontent.com/2241689/45981354-b56c6100-c022-11e8-8dbb-6bf5b9173824.png)

**Comment by psarahdactyl** [comment]
This is the output now, with fills excluded:
<img width="260" alt="art_flattened" src="https://user-images.githubusercontent.com/5149074/46626875-a4355100-cb06-11e8-92e6-9a7dc08467a8.PNG">


[art.svg_flattened.svg.zip](https://github.com/psarahdactyl/wysiwyc/files/2457219/art.svg_flattened.svg.zip)
