### ISSUE TITLE
Exploder svg's do not render in browser

### ISSUE THREAD

**Issue by psarahdactyl** [psarahdactyl/wysiwyc#4]
Exploder outputs valid svg's that can be opened in illustrator, but they can't be seen in the browser because of the xml namespace not being output into the resulting file.

**Comment by vemodalen** [comment]
Was able to duplicate and fix this issue. Are you able to open them in the browser now?

**Comment by psarahdactyl** [comment]
Yep, perfect!

**Comment by psarahdactyl** [comment]
Although, it seems like the exploding part doesn't happen anymore.
